// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MovieWebsite.Models;

namespace MovieWebsite.Migrations
{
    [DbContext(typeof(MovieEntriesContext))]
    [Migration("20220202181707_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.22");

            modelBuilder.Entity("MovieWebsite.Models.Category", b =>
                {
                    b.Property<int>("CategoryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CategoryName")
                        .HasColumnType("TEXT");

                    b.HasKey("CategoryID");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryID = 1,
                            CategoryName = "Action/Thriller"
                        },
                        new
                        {
                            CategoryID = 2,
                            CategoryName = "Drama"
                        },
                        new
                        {
                            CategoryID = 3,
                            CategoryName = "Family"
                        },
                        new
                        {
                            CategoryID = 4,
                            CategoryName = "Comedy"
                        });
                });

            modelBuilder.Entity("MovieWebsite.Models.Movies", b =>
                {
                    b.Property<int>("MovieID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CategoryID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Director")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Edited")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Lent_To")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT")
                        .HasMaxLength(25);

                    b.Property<string>("Rating")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Year")
                        .HasColumnType("INTEGER");

                    b.HasKey("MovieID");

                    b.HasIndex("CategoryID");

                    b.ToTable("movies");

                    b.HasData(
                        new
                        {
                            MovieID = 1,
                            CategoryID = 1,
                            Director = "Doug Liman",
                            Edited = false,
                            Lent_To = "Cousin Ben",
                            Notes = "Loved it! Very intense.",
                            Rating = "PG-13",
                            Title = "The Bourne Identity",
                            Year = 2002
                        },
                        new
                        {
                            MovieID = 2,
                            CategoryID = 2,
                            Director = "John Lee Hancock",
                            Edited = true,
                            Lent_To = "",
                            Notes = "",
                            Rating = "PG-13",
                            Title = "The Blind Side",
                            Year = 2009
                        },
                        new
                        {
                            MovieID = 3,
                            CategoryID = 3,
                            Director = "Dan Scanlon",
                            Edited = false,
                            Lent_To = "",
                            Notes = "even better than the first!",
                            Rating = "G",
                            Title = "Monsters University",
                            Year = 2013
                        });
                });

            modelBuilder.Entity("MovieWebsite.Models.Movies", b =>
                {
                    b.HasOne("MovieWebsite.Models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
