// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MovieWebsite.Models;

namespace MovieWebsite.Migrations
{
    [DbContext(typeof(MovieEntriesContext))]
    [Migration("20220127052247_Submission")]
    partial class Submission
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.22");

            modelBuilder.Entity("MovieWebsite.Models.Movies", b =>
                {
                    b.Property<int>("MovieID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Director")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Edited")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Lent_To")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT")
                        .HasMaxLength(25);

                    b.Property<string>("Rating")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Year")
                        .HasColumnType("INTEGER");

                    b.HasKey("MovieID");

                    b.ToTable("movies");

                    b.HasData(
                        new
                        {
                            MovieID = 1,
                            Category = "Action/Thriller",
                            Director = "Doug Liman",
                            Edited = false,
                            Lent_To = "Cousin Ben",
                            Notes = "Loved it! Very intense.",
                            Rating = "PG-13",
                            Title = "The Bourne Identity",
                            Year = 2002
                        },
                        new
                        {
                            MovieID = 2,
                            Category = "Drama",
                            Director = "John Lee Hancock",
                            Edited = true,
                            Lent_To = "",
                            Notes = "",
                            Rating = "PG-13",
                            Title = "The Blind Side",
                            Year = 2009
                        },
                        new
                        {
                            MovieID = 3,
                            Category = "Family",
                            Director = "Dan Scanlon",
                            Edited = false,
                            Lent_To = "",
                            Notes = "even better than the first!",
                            Rating = "G",
                            Title = "Monsters University",
                            Year = 2013
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
